#workspace state
#Wed May 27 17:30:33 CST 2026
active=F\:\\2.2nd_semester\\OOT\\lab1\\lab1.2\\a.xml
logGlobal=true
open.0.log=true
open.0.modified=false
open.0.path=F\:\\2.2nd_semester\\OOT\\lab1\\lab1.2\\a.txt
open.1.log=false
open.1.modified=false
open.1.path=F\:\\2.2nd_semester\\OOT\\lab1\\lab1.2\\b.txt
open.2.log=false
open.2.modified=false
open.2.path=F\:\\2.2nd_semester\\OOT\\lab1\\lab1.2\\c.txt
open.3.log=false
open.3.modified=false
open.3.path=F\:\\2.2nd_semester\\OOT\\lab1\\lab1.2\\a.xml
open.count=4
