#workspace state
#Mon Apr 27 23:08:48 CST 2026
active=F\:\\2.2nd_semester\\OOT\\lab1.1\\lab2.txt
logGlobal=true
open.0.log=true
open.0.modified=false
open.0.path=F\:\\2.2nd_semester\\OOT\\lab1.1\\lab2.txt
open.count=1
